--- #YAML:1.0
name:                KeyedMutex
version:             0.06
abstract:            An interprocess keyed mutex
license:             ~
author:              
    - Kazuho Oku
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Digest::MD5:                   0
    File::Remove:                  0
    Regexp::Common:                0
    Test::Pod::Coverage:           1.04
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
